using System;
using System.Drawing;
using System.Data;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Reklamacje_Dane
{
    public partial class FormPrzypomnienia : Form
    {
        private readonly PrzypomnieniaService _service;

        public FormPrzypomnienia()
        {
            InitializeComponent();
            _service = new PrzypomnieniaService(new DatabaseService(DatabaseHelper.GetConnectionString()));

            // Konfiguracja filtrów (kolejność ma znaczenie dla SelectedIndex=0)
            cmbFiltr.Items.Clear();
            cmbFiltr.Items.AddRange(new object[] {
                "Wszystkie aktywne", // Zmieniam domyślny na Wszystkie, żebyś na pewno coś widział
                "Moje aktywne",
                "Zaległe",
                "Zrealizowane dzisiaj"
            });
            cmbFiltr.SelectedIndex = 0;

            // Zdarzenia
            this.Load += async (s, e) => await LoadDataAsync();
            this.btnOdswiez.Click += async (s, e) => await LoadDataAsync();
            this.cmbFiltr.SelectedIndexChanged += async (s, e) => await LoadDataAsync();

            this.dgvPrzypomnienia.RowPrePaint += DgvPrzypomnienia_RowPrePaint;
            this.dgvPrzypomnienia.CellDoubleClick += DgvPrzypomnienia_CellDoubleClick;
        

            // Włącz sprawdzanie pisowni dla wszystkich TextBoxów
            EnableSpellCheckOnAllTextBoxes();
        }

        private async Task LoadDataAsync()
        {
            try
            {
                string filter = cmbFiltr.SelectedItem?.ToString();
                var dt = await _service.GetRemindersAsync(filter, Program.fullName);
                dgvPrzypomnienia.DataSource = dt;
                FormatGrid();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Błąd: " + ex.Message);
            }
        }

        private void FormatGrid()
        {
            // Ukrywamy wszystko co niepotrzebne z Twojego zrzutu SQL
            string[] hiddenCols = {
                "Id", "KtoUtworzyl", "DataOstatniejAkcji", "OstatniaAkcjaPrzez",
                "CzyZrealizowane", "IsAutoGenerated", "ReminderType", "DaysValue",
                "created_at", "DataRealizacji"
            };

            foreach (var col in hiddenCols)
            {
                if (dgvPrzypomnienia.Columns.Contains(col)) dgvPrzypomnienia.Columns[col].Visible = false;
            }

            // Ustawiamy ładne nazwy dla widocznych kolumn
            if (dgvPrzypomnienia.Columns.Contains("Tresc"))
            {
                dgvPrzypomnienia.Columns["Tresc"].HeaderText = "Treść Zadania";
                dgvPrzypomnienia.Columns["Tresc"].AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            }
            if (dgvPrzypomnienia.Columns.Contains("DotyczyZgloszenia"))
            {
                dgvPrzypomnienia.Columns["DotyczyZgloszenia"].HeaderText = "Nr Zgłoszenia";
                dgvPrzypomnienia.Columns["DotyczyZgloszenia"].Width = 100;
            }
            if (dgvPrzypomnienia.Columns.Contains("DataPrzypomnienia"))
            {
                dgvPrzypomnienia.Columns["DataPrzypomnienia"].HeaderText = "Termin";
                dgvPrzypomnienia.Columns["DataPrzypomnienia"].Width = 140;
                dgvPrzypomnienia.Columns["DataPrzypomnienia"].DefaultCellStyle.Format = "yyyy-MM-dd HH:mm";
            }
            if (dgvPrzypomnienia.Columns.Contains("PrzypisanyUzytkownik"))
                dgvPrzypomnienia.Columns["PrzypisanyUzytkownik"].HeaderText = "Dla kogo";

            if (dgvPrzypomnienia.Columns.Contains("Status"))
                dgvPrzypomnienia.Columns["Status"].HeaderText = "Status";

            if (dgvPrzypomnienia.Columns.Contains("Priorytet"))
                dgvPrzypomnienia.Columns["Priorytet"].HeaderText = "Priorytet";
        }

        private void DgvPrzypomnienia_RowPrePaint(object sender, DataGridViewRowPrePaintEventArgs e)
        {
            if (e.RowIndex < 0) return;
            var row = dgvPrzypomnienia.Rows[e.RowIndex];

            // 1. Priorytet
            string prio = row.Cells["Priorytet"].Value?.ToString();
            // Twoja baza ma "Normalny", a ja w kodzie szukałem "Wysoki" - dodaję obsługę
            if (row.Cells["Tresc"].Value != null && row.Cells["Tresc"].Value.ToString().Contains("[PILNE]"))
            {
                row.DefaultCellStyle.BackColor = Color.MistyRose; // Czerwonawe tło dla PILNYCH
            }

            // 2. Termin
            if (row.Cells["DataPrzypomnienia"].Value != DBNull.Value)
            {
                if (DateTime.TryParse(row.Cells["DataPrzypomnienia"].Value.ToString(), out DateTime termin))
                {
                    // Jeśli termin minął i zadanie nie jest Completed
                    string status = row.Cells["Status"].Value?.ToString();
                    if (termin < DateTime.Now && status != "Completed")
                    {
                        row.Cells["DataPrzypomnienia"].Style.ForeColor = Color.Red;
                        row.Cells["DataPrzypomnienia"].Style.Font = new Font(dgvPrzypomnienia.Font, FontStyle.Bold);
                    }
                }
            }

            // 3. Wykonane
            if (row.Cells["Status"].Value?.ToString() == "Completed")
            {
                row.DefaultCellStyle.ForeColor = Color.Gray;
            }
        }

        // --- AKCJE --- (Bez zmian, tylko wywołania)
        private async void itemWykonane_Click(object sender, EventArgs e)
        {
            if (dgvPrzypomnienia.CurrentRow == null) return;
            int id = Convert.ToInt32(dgvPrzypomnienia.CurrentRow.Cells["Id"].Value);
            if (MessageBox.Show("Zakończyć zadanie?", "Potwierdź", MessageBoxButtons.YesNo) == DialogResult.Yes)
            {
                await _service.MarkAsDoneAsync(id, Program.fullName);
                await LoadDataAsync();
            }
        }

        private async void itemPrzelozJutro_Click(object sender, EventArgs e)
        {
            if (dgvPrzypomnienia.CurrentRow == null) return;
            int id = Convert.ToInt32(dgvPrzypomnienia.CurrentRow.Cells["Id"].Value);
            await _service.SnoozeAsync(id, 1, Program.fullName);
            await LoadDataAsync();
        }

        private async void itemPrzelozTydzien_Click(object sender, EventArgs e)
        {
            if (dgvPrzypomnienia.CurrentRow == null) return;
            int id = Convert.ToInt32(dgvPrzypomnienia.CurrentRow.Cells["Id"].Value);
            await _service.SnoozeAsync(id, 7, Program.fullName);
            await LoadDataAsync();
        }

        private void DgvPrzypomnienia_CellDoubleClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            string nrZgl = dgvPrzypomnienia.Rows[e.RowIndex].Cells["DotyczyZgloszenia"].Value?.ToString();
            if (!string.IsNullOrEmpty(nrZgl) && nrZgl.Contains("/"))
            {
                new Form2(nrZgl).Show();
            }
        }

        private async void btnDodajNowe_Click(object sender, EventArgs e)
        {
            // Zakładam, że FormDodajPrzypomnienie już masz i działa
            using (var form = new FormDodajPrzypomnienie())
            {
                if (form.ShowDialog(this) == DialogResult.OK) await LoadDataAsync();
            }
        }
    
        /// <summary>
        /// Włącza sprawdzanie pisowni po polsku dla wszystkich TextBoxów w formularzu
        /// </summary>
        private void EnableSpellCheckOnAllTextBoxes()
        {
            try
            {
                // Włącz sprawdzanie pisowni dla wszystkich kontrolek typu TextBox i RichTextBox
                foreach (Control control in GetAllControls(this))
                {
                    if (control is RichTextBox richTextBox)
                    {
                        richTextBox.EnableSpellCheck(true);
                    }
                    else if (control is TextBox textBox && !(textBox is SpellCheckTextBox))
                    {
                        // Dla zwykłych TextBoxów - bez podkreślania (bo nie obsługują kolorów)
                        textBox.EnableSpellCheck(false);
                    }
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"Błąd włączania sprawdzania pisowni: {ex.Message}");
            }
        }

        /// <summary>
        /// Rekurencyjnie pobiera wszystkie kontrolki z kontenera
        /// </summary>
        private IEnumerable<Control> GetAllControls(Control container)
        {
            foreach (Control control in container.Controls)
            {
                yield return control;

                if (control.HasChildren)
                {
                    foreach (Control child in GetAllControls(control))
                    {
                        yield return child;
                    }
                }
            }
        }
}
}